SalesforceCommerceCloud/raml-toolkit

package.json
src/index.ts
test/main.test.ts
test/utils.test.ts

If an api didn't conform we were still returning a 0 exit code.  Only if it couldn't load the file at all was it returning a non-zero exit code.

Bugfix so when we have an invalid file it returns the proper code:

---

package-lock.json
package.json
src/index.ts
src/logger.ts
test/logger.test.ts

Added logger using loglevel npm package
**Using logger inside the tool to log mesaages**
```javascript
import { ramlToolLogger } from "../logger";
ramlToolLogger.info("info message");
```

Logger for raml-toolkit

---

src/exchange-connector/resourceLoader/fatRamlResourceLoader.ts
src/validator.ts
test/exchange-connector/resourceLoader/fatRamlResourceLoader.test.ts

PR contains the fix for multiple exchange_modules/ in the fat RAML resource path

Use last index of exchange_modules/ as the URI path

---

.circleci/config.yml
LICENSE.txt
app.js
bin/run
package-lock.json
package.json
profiles/mercury.raml
src/exchange-connector/bearerToken.ts
src/exchange-connector/exchangeDirectoryParser.ts
src/exchange-connector/exchangeDownloader.ts
src/exchange-connector/exchangeTypes.ts
src/exchange-connector/index.ts
test/exchange-connector/bearerToken.test.ts
test/exchange-connector/exchangeDirectoryParser.test.ts
test/exchange-connector/exchangeDownloader.test.ts
test/exchange-connector/exchangeTools.test.ts
test/main.test.ts
test/mercury/camelcase-method-displayname.test.ts
test/mercury/camelcase-query-parameters.test.ts
test/mercury/mercury-profile.test.ts
test/mercury/no-literal-question-marks-in-parameters.test.ts
test/mercury/no-literal-question-marks-in-property-names.test.ts
test/utils.test.ts

- Update the amf-client version to 4.0.4
- Update mercury profile to use the new AMF vocabulary
- Replace npm install with npm ci
- Change copyright year to 2020

Update mercury profile to use the new AMF vocabulary

---

README.md
profiles/mercury.raml
src/validator.ts
test/mercury.raml
test/mercury/base-uri-pattern.test.ts

There should be a base uri and it should match this pattern:
https://{shortCode}.api.commercecloud.salesforce.com/test-family/test-api/{version}

Add a rule to check baseUri pattern

---

profiles/mercury.raml
test/mercury/base-uri-pattern.test.ts

* Allow a forward slash at the end of the base uri
* Fix the regex so that the rule doesn't fail if the api family and the api name have more than two words
* Add more tests

Update the base uri rule

---

.snyk
package-lock.json
package.json

Snyk doesn't sign commits, so this is a signed version of the changes in #27, #28.
#27 fixes a lodash prototype pollution vulnerability by adding snyk as a dependency.
#28 updates @oclif/config to a newer version.

Redo Snyk PRs #27, #28

---

package-lock.json
package.json
src/validator.ts
test/validator.test.ts

Need to write a test for this, but basically someone writing profiles without this they would always get the following error regardless.
```
➜  raml-toolkit git:(master) ✗ ./bin/run -p aip test/mercury.raml 
(node:84603) UnhandledPromiseRejectionWarning
(node:84603) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:84603) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
The error now looks like
```
➜  raml-toolkit git:(master) ✗ ./bin/run -p aip …
```

Provide error message when profile fails to parse

---

src/diffTool/rulesProcessor.ts
src/exchange-connector/exchangeDirectoryParser.ts
src/parser.ts
src/validator.ts
test/parser.test.ts
test/validator.test.ts

1. There are existing types that serve the same purpose as the intersection types removed.
2. The param type and return type for `resolveApiModel` were unnecessarily over-specific.
3. Cleaned up linter warnings and type annotations.
4. *Changed return type of `parseRamlFile` and `resolveApiModel` to `Document` instead of `BaseUnit`* because it's more accurate and reduces need for type assertions downstream.

Avoid using intersection types and fix wrong types.

---

src/download/exchangeDownloader.test.ts
src/download/exchangeDownloader.ts
src/download/exchangeTypes.ts

I noticed that this file used `JSON` as a type in a few places. That is not a valid type, it refers to the global JSON stringify/parse object. So I fixed that and a few other inaccurate type annotations. I also cleaned up a few of the functions.
I made one important change. `getSpecificApi` previously returned a Promise or null. I changed it always return a Promise (that could resolve to null), because having a mixed return type can add unnecessary complexity to the code that calls it. This change is technically a breaking change, because the function is a top-level export of the package. However, my next PR will be migrating code from commerce-sdk to here, so it will no longer need to be exported.

Fix invalid types

---

src/lint/index.test.ts
src/lint/index.ts

`raml-toolkit lint --help` showed typescript files as options for the profile flag. Now it doesn't.

Prevent ts files showing as profile options.

---

package-lock.json
package.json

This PR contains the npm audit fixes for snyk alerts
Tested the updates by
- change to raml-toolkit dir
- npm pack
- npx commerce-apps-raml-toolkit-0.4.1.tgz ../commerce-sdk/apis/shopper-search/shopper-search.raml -p mercury

npm audit fixes for third party dependencies

---

package.json
resources/diff/rules/defaultRules.json
src/diff/changes/nodeChanges.test.ts
src/diff/changes/nodeChanges.ts
src/diff/defaultRules.test.ts

Included changes
- New default rule to ignore example changes
- Test cases for default rule and node type structural changes
- Sorted package.json

New Ignore rule for difftool to ignore the changes in RAML examples

---

package-lock.json
package.json
src/common/parser.test.ts
src/download/exchangeDownloader.test.ts
src/lint/lint.test.ts
src/lint/lint.ts

W-7879769 : Fix broken tests in raml-toolkit
Some tests which utilized mocha's `eventually` were not waiting for the promise to return before finishing the test.
A lint rule has been added to ensure tests that use `eventually` now return the actual result.
All tests now comply with the linting rule.
Any broken tests have been fixed.

(Final Review) Added lint rule ensuring all tests eventually return, and fixing broken tests

---

.snyk
package-lock.json
package.json

This PR is part of W-8038871 ticket to utilize the minor deployment tags while downloading the Mercury RAMLs. 
PR Contains: 
- A quick npm audit fix and .snyk updates 
Tests:
- compiles and Builds
- used npm pack to test raml-toolkit manual

npm audit fixes and .snyk updates

---

README.md
package-lock.json
src/diff/changes/apiCollectionChanges.test.ts
src/diff/changes/apiCollectionChanges.ts
src/diff/diffCommand.test.ts
src/diff/diffCommand.ts
src/diff/diffDirectories.test.ts
src/diff/diffDirectories.ts

* Refactor diffDirectories to use the new api structure which replaces api-config.json with .metadata.json
* Load base and new api directories into ApiMetadata trees, and then traverse and compare both the trees
* Update diff directory tests to test the new logic

Refactor directory diff to use api models

---

package-lock.json
resources/lint/profiles/mercury.profile.test.ts
resources/lint/profiles/mercury.raml
resources/lint/profiles/slas.raml
src/generate/handlebarsAmfHelpers.test.ts
src/generate/handlebarsAmfHelpers.ts
src/generate/handlebarsAmfHelpersGetType.test.ts
src/generate/utils.test.ts
src/generate/utils.ts
testResources/generate/handlebarsAmfHelpersTestUtils.ts

* isTypeDefinition returns true for arrays
* isTypeDefinitionArrray added to determine if a type is an array
* getTypeFromShape returns Array<T> if the Shape is a simple array, the name if the array is a data type definition
* Disable upper-camelcase-datatype rule as it is currently broken
* Was able to generate commerce-sdk and commerce-sdk-react with these changes
commerce-sdk PR that uses these changes - https://github.com/SalesforceCommerceCloud/commerce-sdk/pull/271
commerce-sdk-react PR that uses these changes - https://github.com/SalesforceCommerceCloud/commerce-sdk-react/pull/10

Fix type determination for arrays 

---

package-lock.json
resources/lint/profiles/slas.profile.test.ts
resources/lint/profiles/slas.raml
resources/lint/profiles/slas.resource-validation.test.ts

SLAS meant to allow endpoints that start with a dot and a recent change broke that. This reverts the change.

Fix SLAS resource-validation-rule

---

resources/diff/rules/defaultRules.json
src/diff/defaultRules.test.ts

Diff sample output
```
Node: #/web-api/end-points/%2Forganizations%2F%7BorganizationId%7D%2Fzones%2F%7BzoneId%7D%2Fspeed-settings/get
[Non-Breaking] Operation Added: getSpeedSettings
Node: #/web-api/end-points/%2Forganizations%2F%7BorganizationId%7D%2Fzones%2F%7BzoneId%7D%2Fspeed-settings/patch
[Non-Breaking] Operation Added: updateSpeedSettings
```

Added Non-Breaking rule to detect addition of  endpoint operations

---

package-lock.json
package.json
src/download/bearerToken.ts
src/download/config.ts
src/download/exchangeDownloader.test.ts
src/download/exchangeDownloader.ts

- Replace "node-fetch" with "make-fetch-happen" which allows passing in retry options
- downloadApi function now throws error when even after retrying it fails to download an api. Earlier it logged the error when a request was unsuccessful.

Add retry option to fetch

---

src/common/structures/name.ts
src/generate/apiModel.test.ts
src/generate/apiModel.ts
src/generate/index.ts
testResources/raml/custom-field-invalid/custom-field-invalid.raml
testResources/raml/custom-field-invalid/exchange.json
testResources/raml/custom-field/custom-field.raml
testResources/raml/custom-field/exchange.json

This PR exposes a custom field, `x-salesforce-sdk-class-name` within the RAML file that is used for the class name for SDK generation. Previously, the class name in the SDK was defined by using the title field. Developers and Technical writers would update the title in the RAML files as they are also used for client facing documentation, leading to unintended downstream impacts onto the SDKs. To help combat these breaking changes, `x-salesforce-sdk-class-name` can be defined explicitly in the RAML file to be used for SDK class name instead of title. If the custom field does not exist, the SDK will use the title by default.
This also allows Isomorphic SDK hot fix to be reverted once the SDK is updated to consume the new RAML toolkit and the Shopper Context RAML is updated to use the custom …

feat: add custom field for class name @W-13013140@

---

package-lock.json
package.json

This PR releases `raml-toolkit@0.5.12`. 
Changes include:
https://github.com/SalesforceCommerceCloud/raml-toolkit/blob/b6c45470835ded23553e15ec50b86dc2fe06b5ca/CHANGELOG.md#L3-L8

Release v0.5.12 - @W-15675290@

---

config.yaml
src/download/exchangeTypes.ts
src/download/index.ts
src/generate/apiModel.ts

Small follow up PR to add a new type that is used in the SDKs. Also cleans up a duplicate config file.

@W-18575180@ Oas support Followup

---

src/generate-from-oas/generateFromOas.ts

Small change to allow the passing of more arguments to openapi-generator.
Required by the node-sdk so we can set `--reserved-words-mappings delete=delete`

@W-17701719@ Allow more flags to be set for openapi generator

---

.github/workflows/test.yml
src/download/downloadCommand.test.ts
src/download/exchangeDirectoryParser.test.ts
src/download/exchangeDownloader.test.ts
src/download/exchangeDownloader.ts
src/download/exchangeDownloaderMultipleVersions.test.ts
src/download/exchangeTypes.ts
testResources/download/resources/getAssetWithMultipleVersionGroups.json

@W-18706176 @W-18763414
1. Get latest version form all the version groups (V1, V2) of an API. This is to suuport Shopper Baskets V1 and V2
2. Remove the deprecated deployment flag
3. Added tests exchangeDirectoryParser to meet the coverage threshold
4. Spilt the test for exchangeDownloader.ts as there is a warning on the file size
5. All the code is behind isOas flag
Testing
1. download command
`node bin/run download --dest=raml-test --search='category:Visibility = "External"' --log-level=debug `
2. ran updateApis script in commerce-isomorphic-sdk

@W-18706176: Changes to download latest release version of the API

---

.eslintrc.json
src/diff/diffCommand.test.ts
src/diff/oasDiff.test.ts
src/diff/oasDiff.ts
src/generate-from-oas/generateCommand.ts
src/generate-from-oas/generateFromOas.ts

This PR fixed the oasdiff command to be compatible with multiple version of the same API. (E.g shopper-basket v2 and v1)
Since we are pulling multiple verserions of the same apis. Some of them will have the same endpoints. When we try to run `oasdiff changlog` on the parent directory (apis vs oldApis). We ran into an error of endpoint duplication.
Loop through the each API folder and run oasdiff instead of the parent directory. This will guarantee there is not duplication in each run and concat the results into a txt file.
- check out code
- npm i
- npm run build
- npm run test
- Observe all the tests are passing
- check out this oas branch for isomorphic https://github.com/SalesforceCommerceCloud/commerce-sdk-isomorphic/pull/198
- Change raml-toolkit to locale dependencies
- `yarn ci`
- …

W 18764378/oasdiff on multi vers of api
